GET http://localhost:8000/api/chef/search-name?name=geeker
Content-Type: application/json

###

DELETE http://localhost:8000/api/crecipe/4/
Content-Type: application/json
Authorization: Token f0aa3d1cb9809704d7a3f12ae1f20025cd8a9577


{
    "title": "Atta maggi noodels",
    "image": "as",
    "ingrediants": "JAI SHRI RAM",
    "steps": "assasaen da sfnajdfnawjonfdoanfoijasifjasionfoesnofinfaijafijzlbijbaijsfnodsnjpogfb aewipbfewijp fi IEW ",
    "chef": "http://localhost:8000/api/chef/2/",
    "category": "http://localhost:8000/api/category/3/"
  }


###

GET http://localhost:8000/api/recipe/4
Content-Type: application/json
# Authorization: Token f0aa3d1cb9809704d7a3f12ae1f20025cd8a9577

{
    "comment": "Me too brother",
    "chef": "http://localhost:8000/api/chef/5/",
    "recipe": "http://localhost:8000/api/recipe/1/"
  }

###

GET http://localhost:8000/api/category/search-cat?name=appatizer
Content-Type: application/json

###

DELETE http://localhost:8000/api/category/1/
Content-Type: application/json

{
  "name": "appatizers"
}

###